<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>test_ground</AssemblyName>
		<PackageId>test_ground</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<OutputPath>../../../Projects/Rinten-Engine/game/.vs/output/</OutputPath>
		<DocumentationFile>../../../Projects/Rinten-Engine/game/.vs/output/test_ground.xml</DocumentationFile>
		<RootNamespace>Rinten</RootNamespace>
		<Nullable>disable</Nullable>
		<DefaultItemExcludes>$(DefaultItemExcludes);**/editor/**;**/unittest/**</DefaultItemExcludes>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Rinten.Internal.GlobalGameNamespace" Static="true" />
		<Using Include="Microsoft.AspNetCore.Components" />
		<Using Include="Microsoft.AspNetCore.Components.Rendering" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.CodeUpgrader.dll"/> 
		<Analyzer Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.Generator.dll"/> 
		<Reference Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.System.dll"/> 
		<Reference Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.Engine.dll"/> 
		<Reference Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.Filesystem.dll"/> 
		<Reference Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.Reflection.dll"/> 
		<Reference Include="../../../Projects/Rinten-Engine/game/bin/managed/Rinten.Mounting.dll"/> 
		<Reference Include="../../../Projects/Rinten-Engine/game/bin/managed/Microsoft.AspNetCore.Components.dll"/> 
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../Projects/Rinten-Engine/game/addons/base/code/Base Library.csproj" />
	</ItemGroup>

</Project>
